/* tslint:disable */
/* eslint-disable */
/**
 * api/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GoLoadDownloadTask } from './GoLoadDownloadTask';
import {
    GoLoadDownloadTaskFromJSON,
    GoLoadDownloadTaskFromJSONTyped,
    GoLoadDownloadTaskToJSON,
    GoLoadDownloadTaskToJSONTyped,
} from './GoLoadDownloadTask';

/**
 * 
 * @export
 * @interface GoLoadGetDownloadTaskResponse
 */
export interface GoLoadGetDownloadTaskResponse {
    /**
     * 
     * @type {Array<GoLoadDownloadTask>}
     * @memberof GoLoadGetDownloadTaskResponse
     */
    downloadTasks?: Array<GoLoadDownloadTask>;
    /**
     * 
     * @type {string}
     * @memberof GoLoadGetDownloadTaskResponse
     */
    totalDownloadTaskCount?: string;
}

/**
 * Check if a given object implements the GoLoadGetDownloadTaskResponse interface.
 */
export function instanceOfGoLoadGetDownloadTaskResponse(value: object): value is GoLoadGetDownloadTaskResponse {
    return true;
}

export function GoLoadGetDownloadTaskResponseFromJSON(json: any): GoLoadGetDownloadTaskResponse {
    return GoLoadGetDownloadTaskResponseFromJSONTyped(json, false);
}

export function GoLoadGetDownloadTaskResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoLoadGetDownloadTaskResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'downloadTasks': json['downloadTasks'] == null ? undefined : ((json['downloadTasks'] as Array<any>).map(GoLoadDownloadTaskFromJSON)),
        'totalDownloadTaskCount': json['totalDownloadTaskCount'] == null ? undefined : json['totalDownloadTaskCount'],
    };
}

export function GoLoadGetDownloadTaskResponseToJSON(json: any): GoLoadGetDownloadTaskResponse {
    return GoLoadGetDownloadTaskResponseToJSONTyped(json, false);
}

export function GoLoadGetDownloadTaskResponseToJSONTyped(value?: GoLoadGetDownloadTaskResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'downloadTasks': value['downloadTasks'] == null ? undefined : ((value['downloadTasks'] as Array<any>).map(GoLoadDownloadTaskToJSON)),
        'totalDownloadTaskCount': value['totalDownloadTaskCount'],
    };
}

