/* tslint:disable */
/* eslint-disable */
/**
 * api/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoLoadCreateSessionResponse
 */
export interface GoLoadCreateSessionResponse {
    /**
     * 
     * @type {string}
     * @memberof GoLoadCreateSessionResponse
     */
    token?: string;
}

/**
 * Check if a given object implements the GoLoadCreateSessionResponse interface.
 */
export function instanceOfGoLoadCreateSessionResponse(value: object): value is GoLoadCreateSessionResponse {
    return true;
}

export function GoLoadCreateSessionResponseFromJSON(json: any): GoLoadCreateSessionResponse {
    return GoLoadCreateSessionResponseFromJSONTyped(json, false);
}

export function GoLoadCreateSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoLoadCreateSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function GoLoadCreateSessionResponseToJSON(json: any): GoLoadCreateSessionResponse {
    return GoLoadCreateSessionResponseToJSONTyped(json, false);
}

export function GoLoadCreateSessionResponseToJSONTyped(value?: GoLoadCreateSessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

