/* tslint:disable */
/* eslint-disable */
/**
 * api/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoLoadAccount
 */
export interface GoLoadAccount {
    /**
     * 
     * @type {string}
     * @memberof GoLoadAccount
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GoLoadAccount
     */
    accountname?: string;
}

/**
 * Check if a given object implements the GoLoadAccount interface.
 */
export function instanceOfGoLoadAccount(value: object): value is GoLoadAccount {
    return true;
}

export function GoLoadAccountFromJSON(json: any): GoLoadAccount {
    return GoLoadAccountFromJSONTyped(json, false);
}

export function GoLoadAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoLoadAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'accountname': json['accountname'] == null ? undefined : json['accountname'],
    };
}

export function GoLoadAccountToJSON(json: any): GoLoadAccount {
    return GoLoadAccountToJSONTyped(json, false);
}

export function GoLoadAccountToJSONTyped(value?: GoLoadAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'accountname': value['accountname'],
    };
}

